CREATE TABLE IF NOT EXISTS users ("id" text, "name" text INDEX USING fulltext WITH (analyzer = 'standard'), "email" text INDEX USING fulltext WITH (analyzer = 'standard'), "country" text INDEX USING fulltext WITH (analyzer = 'standard'), "code" text INDEX USING fulltext WITH (analyzer = 'standard'), PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS messages ("id" TEXT, "text" TEXT INDEX USING FULLTEXT WITH (analyzer = 'standard'), "author" TEXT, PRIMARY KEY ("id"));


INSERT INTO users (id, NAME, email, country, code)
VALUES (1, 'Phillip Gould', 'vitae@Nuncmauris.ca', 'Indonesia', '406134') ,
       (2, 'Ivory Barry', 'tincidunt.adipiscing@mifelis.ca', 'Belarus', 'L92 4KX') ,
       (3, 'Maggy Deleon', 'mollis.Integer.tincidunt@liberolacusvarius.ca', 'Bermuda', '04195') ,
       (4, 'Linda Sampson', 'fringilla.purus.mauris@Mauris.co.uk', 'Tajikistan', '36473') ,
       (5, 'Rosalyn Tucker', 'nulla@mieleifendegestas.co.uk', 'Saint Barthélemy', '14269') ,
       (6, 'Thomas Roach', 'egestas.Duis.ac@Phasellus.org', 'Lithuania', '93171') ,
       (7, 'Amir Beasley', 'in.consequat.enim@luctus.org', 'Andorra', '59069') ,
       (8, 'Driscoll Gallegos', 'ac@ipsumPhasellusvitae.co.uk', 'Jersey', '70803') ,
       (9, 'Bernard Harding', 'lacus@urnaconvalliserat.com', 'Morocco', '18589') ,
       (10, 'Rose Knox', 'imperdiet.non.vestibulum@necorciDonec.edu', 'Thailand', '8173') ,
       (11, 'Shelley Strong', 'nec.diam@ornarelectus.net', 'Belize', '72997') ,
       (12, 'Mannix Le', 'semper.pretium@Quisque.co.uk', 'Bermuda', '2234') ,
       (13, 'Armando Curtis', 'pede.sagittis@morbitristiquesenectus.edu', 'Macedonia', '78547') ,
       (14, 'Daria Durham', 'est.mollis@Praesentinterdum.com', 'Timor-Leste', '244786') ,
       (15, 'Driscoll Dyer', 'lectus.pede.ultrices@vulputateposuere.com', 'Mexico', '4479') ,
       (16, 'Cyrus Holman', 'orci.adipiscing@sociosquadlitora.org', 'Jamaica', '19996-00340') ,
       (17, 'Garrett Whitney', 'congue.a@afeugiat.com', 'San Marino', '54392') ,
       (18, 'Vladimir Copeland', 'molestie.dapibus@Integer.net', 'Malaysia', '75535') ,
       (19, 'Xanthus Walters', 'luctus.felis@Duis.net', 'Madagascar', 'G8W 1A1') ,
       (20, 'Olivia Joseph', 'Nunc@natoquepenatibuset.ca', 'Bahamas', 'T3S 2W3') ,
       (21, 'Melodie Vance', 'odio@tempor.net', 'Guam', '5780') ,
       (22, 'Chloe Mendoza', 'ante.iaculis@at.com', 'Holy See (Vatican City State)', '3207') ,
       (23, 'Elaine Mejia', 'et.eros@ultricessitamet.ca', 'Antigua and Barbuda', '107823') ,
       (24, 'Raven Burch', 'est.mollis.non@eu.ca', 'New Caledonia', '14750') ,
       (25, 'Denton Bird', 'ut@eu.net', 'Saint Lucia', 'FF5 6DP') ,
       (26, 'Louis Henderson', 'eu@fringilla.org', 'Cape Verde', '68054') ,
       (27, 'Imogene Mckinney', 'aliquet.vel.vulputate@consectetuerrhoncusNullam.co.uk', 'Maldives', '13660') ,
       (28, 'Kibo Rivas', 'Morbi.non.sapien@vitae.com', 'Estonia', '2443') ,
       (29, 'Belle Flowers', 'interdum.feugiat.Sed@Nunclectuspede.edu', 'Bonaire, Sint Eustatius and Saba', '08408') ,
       (30, 'Ila Tucker', 'vehicula@lobortisClass.ca', 'Seychelles', '32695') ,
       (31, 'Jena Best', 'sapien.Aenean.massa@diamnunc.ca', 'Yemen', '763662') ,
       (32, 'Brendan Deleon', 'et@eratSed.com', 'Dominica', '323703') ,
       (33, 'Leilani Phillips', 'dignissim.lacus@loremsemperauctor.org', 'Kenya', 'Q7 4JX') ,
       (34, 'Slade Meyer', 'quis.diam@Crassed.ca', 'Zambia', '458656') ,
       (35, 'Irene Rosales', 'enim.condimentum@loremtristique.com', 'Norfolk Island', '9378') ,
       (36, 'Arden Rodriguez', 'aliquet@nulla.net', 'Liechtenstein', 'H3A 2HK') ,
       (37, 'Rooney Castro', 'sagittis.augue@eteros.net', 'Peru', '3254') ,
       (38, 'Ira Montgomery', 'ac.metus.vitae@egestas.edu', 'Germany', 'Z4221') ,
       (39, 'Cadman Solomon', 'augue.Sed.molestie@ullamcorperDuis.edu', 'Paraguay', '50227') ,
       (40, 'Arden Frederick', 'non@vehiculaaliquetlibero.edu', 'Egypt', '213455') ,
       (41, 'Josephine Rogers', 'venenatis.lacus@Vivamus.net', 'Åland Islands', 'G8B 8G3') ,
       (42, 'Quon Ellison', 'Aliquam@mauris.com', 'Guyana', 'F2G 3IG') ,
       (43, 'Jelani Lambert', 'tempor.erat.neque@at.co.uk', 'Guyana', '01668') ,
       (44, 'Galvin Wagner', 'dui@quispede.org', 'Botswana', '498203') ,
       (45, 'Jorden Pacheco', 'venenatis.lacus.Etiam@maurisblanditmattis.ca', 'Zimbabwe', 'L6K 8W6') ,
       (46, 'Ulric Stephenson', 'molestie.sodales@laoreetipsumCurabitur.edu', 'French Polynesia', '13043') ,
       (47, 'Jessica Mccarty', 'Donec@Aliquamauctor.org', 'United Arab Emirates', '63902') ,
       (48, 'Larissa Barnes', 'rhoncus@venenatisvelfaucibus.edu', 'Portugal', '03248') ,
       (49, 'Keaton Carr', 'odio.sagittis@facilisisloremtristique.co.uk', 'Luxembourg', 'MU4H 8DB') ,
       (50, 'Rooney Hall', 'tortor.nibh@tempor.co.uk', 'Faroe Islands', '407305') ,
       (51, 'Edan Jarvis', 'Phasellus.nulla.Integer@enimnisl.edu', 'Timor-Leste', '10039') ,
       (52, 'Lucy Molina', 'Curabitur.massa@Proinultrices.ca', 'Cook Islands', '883379') ,
       (53, 'Wallace Morgan', 'vel.quam.dignissim@molestietellus.com', 'Virgin Islands, United States', '20980-40220') ,
       (54, 'Mikayla Miller', 'pede.blandit.congue@faucibusorciluctus.edu', 'Mexico', '3864') ,
       (55, 'Norman Dejesus', 'Morbi.sit@vitaesodales.ca', 'Togo', '309803') ,
       (56, 'Walker Conway', 'rhoncus.Donec.est@orcitinciduntadipiscing.edu', 'Chile', '227418') ,
       (57, 'Palmer Bartlett', 'tempor.est.ac@arcu.com', 'Benin', '18629-850') ,
       (58, 'Shelly Montoya', 'sapien.Cras@nuncrisusvarius.org', 'Morocco', '64103-901') ,
       (59, 'Velma Garner', 'non.quam@orci.com', 'Luxembourg', '515337') ,
       (60, 'Dylan Baird', 'lorem.eu.metus@Suspendisseeleifend.co.uk', 'Mali', '4143') ,
       (61, 'Berk Riley', 'Sed@utipsum.edu', 'Eritrea', '427685') ,
       (62, 'Lev Dalton', 'nunc.risus@metusAliquam.org', 'Montenegro', '00518') ,
       (63, 'Stone Wilkerson', 'nisl.elementum@Nullam.org', 'Christmas Island', 'Y2Z 8L7') ,
       (64, 'Sierra Oliver', 'commodo.tincidunt@fermentum.com', 'Philippines', '2368') ,
       (65, 'Reese Rosa', 'facilisis@Nuncsollicitudin.com', 'El Salvador', 'T2T 4C3') ,
       (66, 'Gillian Savage', 'eget@ipsum.edu', 'Russian Federation', '08351') ,
       (67, 'Rinah Serrano', 'felis.eget.varius@lobortis.co.uk', 'Seychelles', '79570') ,
       (68, 'Flynn Cameron', 'tristique.neque@magnaUt.edu', 'Palestine, State of', '52837-32752') ,
       (69, 'Britanney Reed', 'augue.ut@quispede.edu', 'Albania', '723807') ,
       (70, 'Griffin Bartlett', 'in@arcu.co.uk', 'Cayman Islands', 'Z5891') ,
       (71, 'Richard Petersen', 'ligula@lectusantedictum.co.uk', 'Serbia', 'P3A 9G3') ,
       (72, 'Minerva Preston', 'montes@ante.co.uk', 'Tajikistan', '16535') ,
       (73, 'Hamilton Turner', 'consectetuer.adipiscing.elit@elementumpurusaccumsan.com', 'Croatia', '6693') ,
       (74, 'Shea Levy', 'libero.mauris@ultrices.net', 'Saint Lucia', 'BU2 4MS') ,
       (75, 'Ella Henderson', 'Ut.sagittis.lobortis@malesuadavelconvallis.org', 'Central African Republic', '1232') ,
       (76, 'Salvador Giles', 'Cras.vulputate@risusDonec.org', 'Indonesia', '3473 WB') ,
       (77, 'Nevada Munoz', 'ornare@necdiamDuis.com', 'Ghana', '153437') ,
       (78, 'Germaine Mcintosh', 'nunc.ullamcorper.eu@Suspendisse.co.uk', 'Tonga', '964536') ,
       (79, 'Ora Merrill', 'sodales.Mauris@Phasellus.ca', 'Algeria', 'B2 2JR') ,
       (80, 'Neil Velasquez', 'pede.ultrices.a@nonummyac.net', 'Haiti', '73184') ,
       (81, 'Linus Rice', 'rhoncus@augueporttitor.ca', 'Mayotte', '43415') ,
       (82, 'Hakeem Gill', 'velit.Quisque@rutrumFusce.net', 'Thailand', '318221') ,
       (83, 'Sharon Jefferson', 'nec@lectusNullamsuscipit.net', 'Qatar', '525182') ,
       (84, 'Bevis Cruz', 'dolor.Fusce@magna.net', 'Libya', '643273') ,
       (85, 'Lois Charles', 'libero.Proin.mi@lobortisultrices.net', 'Mauritania', 'Z0238') ,
       (86, 'Jameson Yang', 'fermentum@Proineget.net', 'New Zealand', '99218-22223') ,
       (87, 'Hadley Oliver', 'a.purus@eunullaat.edu', 'New Caledonia', '280324') ,
       (88, 'Cain Knowles', 'dictum@acfacilisis.com', 'Thailand', '067085') ,
       (89, 'Mannix Knox', 'a.malesuada@montesnascetur.co.uk', 'Algeria', '76047') ,
       (90, 'Quincy Cummings', 'risus@suscipitest.com', 'Azerbaijan', 'KA7 7IV') ,
       (91, 'David Davenport', 'tristique.senectus.et@Sed.org', 'Martinique', '13358') ,
       (92, 'Wylie Porter', 'ipsum@atlibero.co.uk', 'Latvia', '600347') ,
       (93, 'Sonia Valenzuela', 'nibh@Aliquam.ca', 'Kenya', '80363-40896') ,
       (94, 'Byron Merritt', 'porttitor@dolorquam.edu', 'Sri Lanka', '441062') ,
       (95, 'Dillon Sampson', 'tincidunt.neque.vitae@aliquetmagna.edu', 'Korea, North', '5835') ,
       (96, 'Josephine Wilder', 'consequat.lectus@metus.com', 'Spain', '9927') ,
       (97, 'Wilma Hayden', 'Quisque.ornare.tortor@Phasellusfermentumconvallis.org', 'Somalia', '126781') ,
       (98, 'Rosalyn Owen', 'luctus.vulputate@eleifendnecmalesuada.co.uk', 'Bolivia', '616628') ,
       (99, 'Holly Jarvis', 'Nullam@Lorem.co.uk', 'Pakistan', '686515') ,
       (100, 'Brenda Clements', 'magnis.dis.parturient@ligulaAenean.com', 'United Arab Emirates', '2555 IP');

INSERT INTO messages (id,text,author)
VALUES (1,'amet ante. Vivamus non lorem vitae odio',2),
       (2,'vestibulum lorem, sit amet',12),
       (3,'justo.',8),
       (4,'felis purus',7),
       (5,'arcu imperdiet',11),
       (6,'tempor',14),
       (7,'ullamcorper. Duis cursus, diam at pretium aliquet,',2),
       (8,'Nulla eget metus eu erat semper rutrum. Fusce',5),
       (9,'amet, consectetuer adipiscing elit. Aliquam auctor, velit',9),
       (10,'vitae sodales nisi',15),
       (11,'tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam',13),
       (12,'amet,',18),
       (13,'lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus',16),
       (14,'nunc id enim. Curabitur massa. Vestibulum accumsan',8),
       (15,'Sed pharetra, felis eget varius ultrices,',5),
       (16,'vehicula et,',20),
       (17,'egestas a, scelerisque sed, sapien. Nunc pulvinar arcu',9),
       (18,'ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede',16),
       (19,'Morbi metus. Vivamus',20),
       (20,'Sed neque. Sed eget lacus. Mauris non',11),
       (21,'lorem. Donec elementum, lorem ut aliquam iaculis,',18),
       (22,'Mauris vestibulum, neque sed dictum eleifend, nunc risus',9),
       (23,'nunc',7),
       (24,'Donec nibh enim, gravida sit amet, dapibus id, blandit',2),
       (25,'enim, sit amet',2),
       (26,'at, iaculis',7),
       (27,'per inceptos hymenaeos. Mauris ut',4),
       (28,'egestas a, dui. Cras pellentesque. Sed dictum. Proin eget',17),
       (29,'lacus. Mauris non dui',20),
       (30,'sociis natoque penatibus et magnis',8),
       (31,'Donec feugiat metus sit amet',4),
       (32,'pretium aliquet, metus urna convallis erat, eget tincidunt dui',7),
       (33,'non quam. Pellentesque habitant morbi tristique senectus et',14),
       (34,'gravida molestie arcu. Sed eu nibh vulputate mauris',13),
       (35,'fringilla. Donec feugiat metus',2),
       (36,'a odio',1),
       (37,'iaculis, lacus pede sagittis augue, eu tempor erat',6),
       (38,'nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat',14),
       (39,'Fusce dolor quam, elementum at, egestas a, scelerisque',12),
       (40,'mi lorem,',6),
       (41,'Donec',19),
       (42,'arcu. Vestibulum ante ipsum primis in faucibus',17),
       (43,'sit amet, consectetuer adipiscing elit. Curabitur',1),
       (44,'orci',16),
       (45,'Vestibulum ante ipsum primis in faucibus orci',8),
       (46,'imperdiet dictum magna. Ut tincidunt',8),
       (47,'tincidunt adipiscing. Mauris molestie',11),
       (48,'orci. Donec nibh. Quisque',13),
       (49,'montes, nascetur',20),
       (50,'magnis dis parturient montes, nascetur ridiculus',19),
       (51,'sem ut dolor dapibus gravida. Aliquam tincidunt, nunc',4),
       (52,'erat neque non quam. Pellentesque habitant morbi',12),
       (53,'tempus non,',14),
       (54,'ac tellus. Suspendisse sed dolor. Fusce mi lorem,',4),
       (55,'Ut tincidunt orci quis lectus. Nullam suscipit, est',14),
       (56,'ipsum dolor',9),
       (57,'a, aliquet vel, vulputate eu, odio. Phasellus at',17),
       (58,'sociis natoque penatibus',13),
       (59,'imperdiet non, vestibulum',8),
       (60,'cursus non, egestas a,',8),
       (61,'odio. Aliquam vulputate',16),
       (62,'aliquet,',13),
       (63,'nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat.',6),
       (64,'mauris. Morbi non',3),
       (65,'ipsum non arcu. Vivamus sit amet risus.',16),
       (66,'tristique',4),
       (67,'nec orci. Donec nibh. Quisque nonummy ipsum non',12),
       (68,'augue id ante dictum cursus. Nunc mauris elit, dictum',4),
       (69,'Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna.',3),
       (70,'cubilia Curae; Donec tincidunt. Donec vitae erat',2),
       (71,'sem egestas blandit.',15),
       (72,'arcu ac orci.',15),
       (73,'ipsum sodales purus, in molestie tortor nibh sit amet orci.',15),
       (74,'Maecenas ornare egestas ligula.',1),
       (75,'sit amet lorem semper auctor.',20),
       (76,'magnis dis parturient montes,',2),
       (77,'vitae, orci. Phasellus dapibus quam',4),
       (78,'Donec dignissim magna a tortor. Nunc',17),
       (79,'ac arcu. Nunc',10),
       (80,'augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum.',2),
       (81,'sed, hendrerit a, arcu. Sed et libero. Proin',9),
       (82,'lobortis augue scelerisque mollis. Phasellus libero',4),
       (83,'ut mi. Duis risus odio, auctor vitae, aliquet',13),
       (84,'nulla vulputate dui, nec tempus mauris',18),
       (85,'interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue',12),
       (86,'malesuada fringilla',6),
       (87,'nulla. Integer urna. Vivamus molestie dapibus',19),
       (88,'Donec nibh enim, gravida sit amet, dapibus',1),
       (89,'felis. Nulla tempor augue ac ipsum.',8),
       (90,'mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla',18),
       (91,'natoque penatibus et magnis',18),
       (92,'nec urna suscipit nonummy.',20);